language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t lgmartins96/docker-react -f Dockerfile.dev build .

script:
  - docker run -e CI=true lgmartins96/docker-react npm run test